import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./components/loginBtn/loginBtn";
import NextAuth, { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  console.log(session)

  return (
    <html lang="ko">
      <body >
        <div className="nav-bar">
          <Link href='/' className="logo">Board</Link>
          <Link href='/list'>List</Link>
          <Link href='/write'>write</Link>
          <LoginBtn login={session}/>
        </div>
        {children}
        </body>
    </html>
  );
}



//소셜로그인 설정
//npm install next-auth
//pages폴더 안에 api폴더 안에 auth폴더 생성하고
// [...nextauth].js파일 생성
// [] : dynamic route (동적 url) : 각 소셜 로그인에서 제공하는 경로를 넣을 것임(구글, 깃허브, 페이스북 등.. 다 다르게 제공)